backend:
  name: github
  repo: morgansegura/catapultarts
  branch: master
publish_mode: editorial_workflow
media_folder: static/images
public_folder: images

display_url: https://catapultarts.netlify.com/

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      
  - name: "pages"
    label: "Pages"
    create: true
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page" }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Main Image",
              name: "mainImage",
              widget: "object",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Image Description", name: "imageAlt", widget: "string" },
                ],
            }
          - { label: "Body", name: "body", widget: "markdown" }
          - {
              label: "Image Gallery",
              name: "gallery",
              widget: "list",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Image Description", name: "imageAlt", widget: "string" },
                ],
            }
          - { label: "Developer Groups", name: "developerGroups", widget: "markdown" }
          - {
              label: "Meetup Organizers",
              name: "organizers",
              widget: "object",
              fields:
                [
                  { label: "Title", name: "title", widget: "string" },
                  {
                    label: "Images",
                    name: "gallery",
                    widget: "list",
                    fields:
                      [
                        { label: "Name", name: "name", widget: "string" },
                        { label: "Image", name: "image", widget: "image" },
                        { label: "Image Description", name: "imageAlt", widget: "string" },
                      ],
                  },
                ],
            }
          - {
              label: "SEO & Meta",
              name: "seo",
              widget: "object",
              fields:
                [
                  { label: "Browser Tab Title", name: "browserTitle", widget: "string"},
                  { label: "Title", name: "title", widget: "string" },
                  { label: "Description", name: "description", widget: "string" },
                ],
            }
      - file: "src/pages/home/index.md"
        label: "Home"
        name: "home"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Upcoming Meetup Heading", name: "upcomingMeetupHeading", widget: "string" }
          - { label: "No Upcoming Meetup Text", name: "noUpcomingMeetupText", hint: "This text will be displayed when there are no upcoming meetups", required: true, widget: "string" }
          - { label: "Maps Note", name: "mapsNote", required: true, widget: "string" }
          - {
              label: "Call to Actions",
              name: "callToActions",
              required: true,
              widget: "object",
              fields:
                [
                  {
                    label: "First CTA",
                    name: "firstCTA",
                    required: true,
                    widget: "object",
                    fields:
                      [
                        { label: "Heading", name: "heading", widget: "string" },
                        { label: "Sub Heading", name: "subHeading", widget: "string" },
                        {
                          label: "Link Type",
                          name: "linkType",
                          widget: "select",
                          options: ["internal", "external"],
                        },
                        {
                          label: "Link URL",
                          name: "linkURL",
                          widget: "string",
                          hint: "Use a relative URL (e.g. /about) if the link is an internal link.",
                        }
                      ]
                  },
                  {
                    label: "Second CTA",
                    name: "secondCTA",
                    required: true,
                    widget: "object",
                    fields:
                      [
                        { label: "Heading", name: "heading", widget: "string" },
                        { label: "Sub Heading", name: "subHeading", widget: "string" },
                        {
                          label: "Link Type",
                          name: "linkType",
                          widget: "select",
                          options: ["internal", "external"],
                        },
                        {
                          label: "Link URL",
                          name: "linkURL",
                          widget: "string",
                          hint: "Use a relative URL (e.g. /about) if the link is an internal link.",
                        }
                      ]
                  }
                ],
            }
          - {
              label: "SEO & Meta",
              name: "seo",
              widget: "object",
              fields:
                [
                  { label: "Browser Tab Title", name: "browserTitle", widget: "string"},
                  { label: "Title", name: "title", widget: "string" },
                  { label: "Description", name: "description", widget: "string" },
                ],
            }
  # Settings Section
  - name: "settings"
    label: "Settings"
    files:
    # Site Settings (Logo and Menu)
      - file: "src/pages/settings/index.md"
        label: "Site Settings"
        name: "settings"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "settings" }       
          - {
              label: "(SEO) Meta Settings <a href='https://catapultarts.com/docs/seo'></a>",
              name: "meta",
              widget: "list",
              fields:
                [
                  { label: "Title", name: "title", widget: "string", hint: "This title will be displayed in the <head> of your website." },
                  { label: "Meta Keywords", name: "metaKeywords", widget: "string", options: ["internal", "external"], hint: "Create a strong meta keywords for your main page." },
                  { label: "Meta Description", name: "metaDesc", widget: "string", hint: "Create a good meta description for your main page." },
                ],
            }
          - {
              label: "Menu Items",
              name: "menuItems",
              widget: "list",
              fields:
                [
                  { label: "Label", name: "label", widget: "string", hint: "The visible text in this link." },
                  { label: "Link Type", name: "linkType", widget: "select", options: ["internal", "external"], hint: "Choose between internal and external." },
                  { label: "Link URL", name: "linkURL", widget: "string", hint: "Use a relative URL (e.g. /about) if the link is an internal link. Otherwise, (e.g. https://google.com)" },
                ],
            }
          - {
              label: "Logo",
              name: "logoImage",
              widget: "object",
              fields:
                [
                  { label: "Image", name: "image", widget: "image", hint: "Upload an image. Leave blank to display text." },
                  { label: "Image Description", name: "imageAlt", widget: "string", hint: "(SEO) The Alt tage for this image." },
                  { label: "Image Width", name: "imageWidth", widget: "number", default: 40, valueType: "int", hint: "The width of your logo in the header in pixels. Default: 40px" },
                  { label: "Image Label", name: "imageLabel", widget: "string", hint: "This text will show up if there is no image." },
                ],
            }             
